language: android
jdk: oraclejdk7
env:
  matrix:
  - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a
android:
  components:
  - build-tools-21.1.2
before_install:
- export ANDROID_HOME=/usr/local/android-sdk
- if [ `uname -m` = x86_64 ]; then wget http://dl.google.com/android/ndk/android-ndk-r10d-linux-x86_64.bin
  -O ndk.bin; else wget http://dl.google.com/android/ndk/android-ndk-r10d-linux-x86.bin
  -O ndk.bin; fi
- sudo apt-get install -y p7zip-full
- 7z x ndk.bin android-ndk-r10d/build/ android-ndk-r10d/ndk-build android-ndk-r10d/platforms/android-21
  > /dev/null
- export ANDROID_NDK_HOME=`pwd`/android-ndk-r10d
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_NDK_HOME}
- echo "sdk.dir=$ANDROID_HOME" > local.properties
- echo "ndk.dir=$ANDROID_NDK_HOME" >> local.properties
script: ./gradlew clean assembleDebug assembleDebugTest :card.io:assembleRelease releaseDoc
notifications:
  webhooks:
    urls:
    - secure: A1YKQ32CBvm6s0gfwb+UKZuniYdb5ZUENvSpSt/k7nQmyZ9U0p4Sn8qqSSKfRyYVRLT3C3za53aoqFwSqFj6mZ82YO6HbKl/RqhGQLmdIPpyhXKUE5xKlyMbgmAYRBDh41+eQ1i22mkT+jiqVW06VFSB0YyeDKAZjXxk8hfyIUA=
    on_success: change
    on_failure: always
